---
# File: roles/eclipse/tasks/main.yml

#
# Install Eclipse Luna JEE/BIRT (SR1)
#

- name: create a directory for optional Eclipse software
  file: name=/opt/eclipse state=directory
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (Juno)
  uri: url=http://carroll.aset.psu.edu/pub/eclipse/technology/epp/downloads/release/luna/SR1/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
       dest=~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
       creates=~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
  tags:
    - eclipse

- name: install the latest version of Eclipse JEE/BIRT (Juno)
  shell: tar -C /opt/eclipse -xzf ~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
         creates=/opt/eclipse/eclipse-reporting-luna-SR1
  tags:
    - eclipse

- name: move the unpacked archive to a more correct location
  shell: mv /opt/eclipse/eclipse /opt/eclipse/eclipse-reporting-luna-SR1
         creates=/opt/eclipse/eclipse-reporting-luna-SR1
  tags:
    - eclipse

- name: make a prettier symlink to the Eclipse installation
  file: src=/opt/eclipse/eclipse-reporting-luna-SR1
        path=/opt/eclipse/luna state=link
  tags:
    - eclipse

- name: add a launcher to the development menu
  copy: src=../files/eclipse.desktop
        dest=/usr/share/applications
  tags:
    - eclipse

#
# SCM Plugin installation
#

- name: add the EGit plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/releases/luna
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.egit.feature.group
    - org.eclipse.jgit.feature.group
    - org.eclipse.emf.sdk.feature.group
    - org.eclipse.mylyn_feature.feature.group
  tags:
    - git

- name: add the Subclipse plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://subclipse.tigris.org/update_1.10.x
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - com.collabnet.subversion.merge.feature.feature.group
    - org.tigris.subversion.subclipse.feature.group
    - org.tigris.subversion.subclipse.mylyn.feature.group
    - org.tigris.subversion.clientadapter.feature.feature.group
    - org.tigris.subversion.clientadapter.javahl.feature.feature.group
    - org.tigris.subversion.subclipse.graph.feature.feature.group
    - org.tigris.subversion.clientadapter.svnkit.feature.feature.group
  tags:
    - subversion

#
# Maven plugin installation
#

- name: M2Eclipse requires additional Eclipse logging plugins (bundles)
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/releases/luna
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.slf4j.api
    - ch.qos.logback.classic
    - ch.qos.logback.slf4j
  tags:
    - maven

- name: add the M2Eclipse plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/technology/m2e/releases
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.m2e.feature.feature.group
    - org.eclipse.m2e.logback.feature.feature.group
  tags:
    - maven

#
# Code quality and test coverage
#

- name: add the Checkstyle plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://eclipse-cs.sourceforge.net/update
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - net.sf.eclipsecs.feature.group
    - com.github.sevntu.checkstyle.checks.feature.feature.group
  tags:
    - quality

- name: add the Findbugs plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://findbugs.cs.umd.edu/eclipse
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - edu.umd.cs.findbugs.plugin.eclipse.feature.group
  tags:
    - quality

- name: add the EclEmma plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://update.eclemma.org
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - com.mountainminds.eclemma.feature.feature.group
  tags:
    - ldap

# TODO (smoyer1) - Add the Sonar plugin

#
# LDAP plugins
#

- name: add the Apache Directory Studio plugins
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://directory.apache.org/studio/update/2.x
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.apache.directory.studio.ldapbrowser.feature.feature.group
    - org.apache.directory.studio.ldifeditor.feature.feature.group
    - org.apache.directory.studio.schemaeditor.feature.feature.group
  tags:
    - coverage

# NOTE (smoyer1) - The update site includes these 7 features
#    - org.apache.directory.studio.apacheds.configuration.feature.feature.group
#    - org.apache.directory.studio.apacheds.configuration.v2.feature.feature.group
#    - org.apache.directory.studio.ldapbrowser.feature.feature.group
#    - org.apache.directory.studio.ldapservers.feature.feature.group
#    - org.apache.directory.studio.ldifeditor.feature.feature.group
#    - org.apache.directory.studio.rcp.feature.feature.group
#    - org.apache.directory.studio.schemaeditor.feature.feature.group

#
# Extra text editors
#

- name: add the YAML Editor plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://dadacoalition.org/yedit
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.dadacoalition.yedit.feature.group
  tags:
    - editors

# TODO (smoyer1) - There are a lot of other cool tools in this repository
- name: add JSON and Markdown Editor plugins
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://www.nodeclipse.org/updates/
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - markdown.editor.feature.feature.group
    - jsonedit-feature.feature.group
    - org.sweetlemonade.eclipse.json.feature.feature.group
  tags:
    - editors

#
# Modeling and Diagraming plugins
#

- name: download the UMLet plugin
  uri: url=http://www.umlet.com/umlet_13_1/com.umlet.plugin_13.1.0.jar
       dest=~/com.umlet.plugin_13.1.0.jar
       creates=~/com.umlet.plugin_13.1.0.jar
  tags:
    - uml
       
- name: install the UMLet plugin
  shell: cp ~/com.umlet.plugin_13.1.0.jar /opt/eclipse/luna/plugins/com.umlet.plugin_13.1.0.jar
         creates=/opt/eclipse/luna/plugins/com.umlet.plugin_13.1.0.jar
  tags:
    - uml

- name: add the ERMaster (ERD) plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://ermaster.sourceforge.net/update-site
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.insightech.er.feature.feature.group
  tags:
    - editors
