---
# File: roles/eclipse/tasks/main.yml
#
# See the following link for information on the p2.director application:
#
# - http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_director.html
#

#
# Install Eclipse Luna JEE/BIRT (SR1)
#

- name: create a directory for optional Eclipse software
  file: name={{ eclipse_installation_directory }}
        state=directory
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (64-bit)
  uri: url={{ eclipse_url_64 }}
       dest=~/{{ eclipse_file_64 }}
       creates=~/{{ eclipse_file_64 }}
  when: ansible_architecture == "x86_64"
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (32-bit)
  uri: url={{ eclipse_url_32 }}
       dest=~/{{ eclipse_file_32 }}
       creates=~/{{ eclipse_file_32 }}
  when: ansible_architecture == "i386"
  tags:
    - eclipse

- name: untar the Eclipse JEE/BIRT archive (64-bit)
  unarchive: copy=no
             src=~/{{ eclipse_file_64 }}
             dest={{ eclipse_installation_directory }}
             creates={{ eclipse_home_directory }}
  when: ansible_architecture == "x86_64"
  register: unarchive_result_64
  tags:
    - eclipse

- name: untar the Eclipse JEE/BIRT archive (32-bit)
  unarchive: copy=no
             src=~/{{ eclipse_file_32 }}
             dest={{ eclipse_installation_directory }}
             creates={{ eclipse_home_directory }}
  when: ansible_architecture == "i386"
  register: unarchive_result_32
  tags:
    - eclipse

- name: move the tar file's base directory somewhere maintainable
  command: mv {{ eclipse_tar_directory }}
           {{ eclipse_home_directory }}
  when: (unarchive_result_64 | changed) or (unarchive_result_32 | changed)
  tags:
    - eclipse

- name: create a pretty symlink to the latest version
  file: src={{ eclipse_home_directory }}
        path={{ eclipse_installation_directory }}/latest
        state=link
  tags:
    - eclipse

- name: add a launcher to the development menu
  copy: src=../files/eclipse.desktop
        dest=/usr/share/applications
  tags:
    - eclipse
    
- name: set JVM arguments in eclipse.ini
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -vmargs -Xms12M -Xmx2048M -XX:PermSize=128M -XX:MaxPermSize=512M
  tags:
    - eclipse

#
# Clean up the directory structure of previous installs
#

- name: check to see if the old directory structure still exists
  stat: path=/opt/eclipse/eclipse-reporting-luna-SR1
  register: luna_sr1_stat

- name: move the luna-SR1 directory to a strict version / R(SR) number
  command: mv /opt/eclipse/eclipse-reporting-luna-SR1
              /opt/eclipse/luna-SR1
  when: luna_sr1_stat.stat.exists

- name: remove the old sym-link to the luna SR1 version
  file: path=/opt/eclipse/luna
        state=absent

#
# SCM Plugin installation 
#

- name: add the EGit plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/egit/updates
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.egit.feature.group
    - org.eclipse.jgit.feature.group
    - org.eclipse.jgit.java7.feature.group
  tags:
    - git

- name: add the EGit - Mylyn interface
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/releases/luna
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.emf.sdk.feature.group
    - org.eclipse.mylyn_feature.feature.group
  tags:
    - git

- name: add the Subclipse plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://subclipse.tigris.org/update_1.10.x
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - com.collabnet.subversion.merge.feature.feature.group
    - org.tigris.subversion.subclipse.feature.group
    - org.tigris.subversion.subclipse.mylyn.feature.group
    - org.tigris.subversion.clientadapter.feature.feature.group
    - org.tigris.subversion.clientadapter.javahl.feature.feature.group
    - org.tigris.subversion.subclipse.graph.feature.feature.group
    - org.tigris.subversion.clientadapter.svnkit.feature.feature.group
  tags:
    - subversion

#
# Maven plugin installation
#

- name: M2Eclipse requires additional Eclipse logging plugins (bundles)
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/releases/luna
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.slf4j.api
    - ch.qos.logback.classic
    - ch.qos.logback.slf4j
  tags:
    - maven

- name: add the M2Eclipse plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/technology/m2e/releases
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.m2e.feature.feature.group
    - org.eclipse.m2e.logback.feature.feature.group
  tags:
    - maven

#
# Code quality and test coverage
#

- name: add the Checkstyle plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://eclipse-cs.sourceforge.net/update
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - net.sf.eclipsecs.feature.group
    - com.github.sevntu.checkstyle.checks.feature.feature.group
  tags:
    - quality

- name: add the Findbugs plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://findbugs.cs.umd.edu/eclipse
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - edu.umd.cs.findbugs.plugin.eclipse.feature.group
  tags:
    - quality

- name: add the EclEmma plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://update.eclemma.org
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - com.mountainminds.eclemma.feature.feature.group
  tags:
    - ldap

# TODO (smoyer1) - Add the Sonar plugin

#
# Extra text editors
#

- name: add the YAML Editor plugin
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://dadacoalition.org/yedit
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.dadacoalition.yedit.feature.group
  tags:
    - editors

# TODO (smoyer1) - There are a lot of other cool tools in this repository
- name: add JSON and Markdown Editor plugins
  shell: >
         /opt/eclipse/latest/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://www.nodeclipse.org/updates
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
#    - markdown.editor.feature.feature.group
    - jsonedit-feature.feature.group
    - org.sweetlemonade.eclipse.json.feature.feature.group
  tags:
    - editors
    
#
# Issue tracking connectors
#

#- name: Atlassian - Mylyn connector requires additional Eclipse plugins (bundles)
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - javax.xml.soap
#    - org.apache.commons.io/2.0.1.v201105210651
#  tags:
#    - issues
#    
#- name: add Atlassian - Mylyn connector
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://update.atlassian.com/atlassian-eclipse-plugin/rest/e3.7
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - com.atlassian.connector.eclipse.feature.group
#  tags:
#    - issues
#    
#- name: add Github - Mylyn connector (requires egit-core > 3.5.x)
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.eclipse.org/egit/github/updates
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - org.eclipse.mylyn.github.feature.feature.group
#  tags:
#    - issues

#
# Framework plugins
#

# NOTE: (smoyer1) - Add Google plugins

#- name: install the JBoss Tools plugin
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.jboss.org/jbosstools/updates/stable/luna
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - org.jboss.tools.cdi.deltaspike.feature.feature.group
#    - org.jboss.tools.arquillian.feature.feature.group
#    - org.jboss.tools.cdi.feature.feature.group
#    - org.jboss.tools.forge.m2e.feature.feature.group
#    - org.jboss.tools.forge.feature.feature.group
#    - org.jboss.tools.forge.ext.feature.feature.group
#    - org.jboss.ide.eclipse.freemarker.feature.feature.group
#    - org.hibernate.eclipse.feature.feature.group
#    - org.jboss.ide.eclipse.archives.feature.feature.group
#    - org.jboss.tools.birt.feature.feature.group
#    - org.jboss.tools.central.themes.feature.feature.group
#    - org.jboss.tools.community.central.feature.feature.group
#    - org.jboss.tools.ws.jaxrs.feature.feature.group
#    - org.jboss.tools.maven.cdi.feature.feature.group
#    - org.jboss.tools.maven.jdt.feature.feature.group
#    - org.jboss.tools.maven.hibernate.feature.feature.group
#    - org.jboss.tools.maven.feature.feature.group
#    - org.jboss.tools.maven.portlet.feature.feature.group
#    - org.jboss.tools.maven.project.examples.feature.feature.group
#    - org.jboss.tools.maven.seam.feature.feature.group
#    - org.jboss.tools.openshift.express.feature.feature.group
#    - org.jboss.tools.portlet.feature.feature.group
#    - org.jboss.tools.runtime.core.feature.feature.group
#    - org.jboss.tools.runtime.seam.detector.feature.feature.group
#    - org.jboss.tools.stacks.core.feature.feature.group
#    - org.jboss.tools.vpe.cordovasim.feature.feature.group
#    - org.jboss.tools.wtp.runtimes.tomcat.feature.feature.group
#    - org.jboss.tools.common.mylyn.feature.feature.group
#    - org.jboss.tools.community.project.examples.feature.feature.group
#    - org.jboss.tools.aerogear.thym.feature.feature.group
#    - org.jboss.tools.openshift.egit.integration.feature.feature.group
#    - org.jboss.tools.foundation.feature.feature.group
#    - org.jboss.tools.foundation.security.linux.feature.feature.group
#    - org.jboss.tools.jst.feature.feature.group
#    - org.jboss.tools.jst.angularjs.feature.feature.group
#    - org.jboss.tools.jst.jsdt.feature.feature.group
#    - org.jboss.tools.common.jdt.feature.feature.group
#    - org.jboss.tools.jsf.feature.feature.group
#    - org.jboss.tools.livereload.feature.feature.group
#    - org.jboss.tools.maven.jbosspackaging.feature.feature.group
#    - org.jboss.tools.maven.sourcelookup.feature.feature.group
#    - org.jboss.tools.vpe.browsersim.feature.feature.group
#    - org.jboss.tools.richfaces.feature.feature.group
#    - org.jboss.tools.usage.feature.feature.group
#    - org.jboss.tools.vpe.feature.feature.group
#    - org.jboss.tools.ws.feature.feature.group
#    - org.jboss.ide.eclipse.as.feature.feature.group
#    - org.jboss.tools.jmx.feature.feature.group
#    - org.jboss.tools.maven.apt.feature.feature.group
#    - org.jboss.tools.project.examples.feature.feature.group
#    - org.jboss.tools.cdi.seam.feature.feature.group
#    - org.jboss.tools.seam.feature.feature.group
#  tags:
#    - wildfly

