---
# File: roles/eclipse/tasks/main.yml

#
# Install Eclipse Luna JEE/BIRT (SR1)
#

- name: create a directory for optional Eclipse software
  file: name=/opt/eclipse state=directory
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (Juno)
  uri: url=http://carroll.aset.psu.edu/pub/eclipse/technology/epp/downloads/release/luna/SR1/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
       dest=~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
       creates=~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
  tags:
    - eclipse

- name: install the latest version of Eclipse JEE/BIRT (Juno)
  shell: tar -C /opt/eclipse -xzf ~/eclipse-reporting-luna-SR1-linux-gtk-x86_64.tar.gz
         creates=/opt/eclipse/eclipse-reporting-luna-SR1
  tags:
    - eclipse

- name: move the unpacked archive to a more correct location
  shell: mv /opt/eclipse/eclipse /opt/eclipse/eclipse-reporting-luna-SR1
         creates=/opt/eclipse/eclipse-reporting-luna-SR1
  tags:
    - eclipse

- name: make a prettier symlink to the Eclipse installation
  file: src=/opt/eclipse/eclipse-reporting-luna-SR1
        path=/opt/eclipse/luna state=link
  tags:
    - eclipse

- name: add a launcher to the development menu
  copy: src=../files/eclipse.desktop
        dest=/usr/share/applications
  tags:
    - eclipse

#
# SCM Plugin installation
#

- name: add the EGit plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://download.eclipse.org/releases/luna
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - org.eclipse.egit.feature.group
    - org.eclipse.jgit.feature.group
    - org.eclipse.emf.sdk.feature.group
    - org.eclipse.mylyn_feature.feature.group
  tags:
    - git

- name: add the Subclipse plugin
  shell: >
         /opt/eclipse/luna/eclipse
         -noSplash
         -application org.eclipse.equinox.p2.director
         -repository http://subclipse.tigris.org/update_1.10.x
         -profileProperties org.eclipse.update.install.features=true
         -installIUs {{ item }}
  with_items:
    - com.collabnet.subversion.merge.feature.feature.group
    - org.tigris.subversion.subclipse.feature.group
    - org.tigris.subversion.subclipse.mylyn.feature.group
    - org.tigris.subversion.clientadapter.feature.feature.group
    - org.tigris.subversion.clientadapter.javahl.feature.feature.group
    - org.tigris.subversion.subclipse.graph.feature.feature.group
    - org.tigris.subversion.clientadapter.svnkit.feature.feature.group
  tags:
    - subversion

#         -profile SDKProfile
