---
# File: roles/cloud/tasks/main.yml

- name: remove AWS CLI tools from Debian repositories
  apt: 
    name: awscli
    state: absent
  tags:
    - cloud
    - aws

- name: remove AWS CLI tools installed via SNAP
  snap:
    name: "aws-cli"
    state: "absent"
    classic: true
  tags:
    - cloud
    - aws

- name: install AWS CLI tools via PIP
  pip:
    name: awscli
    extra_args: --upgrade
    state: latest
  tags:
    - cloud
    - aws

- name: install latest Azure CLI tools via SNAP
  snap:
    name: "azure-cli"
    channel: "candidate"
    state: "present"
  tags:
    - cloud
    - azure
