---
# File: roles/cloud/tasks/main.yml

- name: remove AWS CLI tools from Debian repositories
  apt: name=awscli state=absent
  tags:
    - cloud
    - aws

- name: remove AWS CLI tools installed via SNAP
  command: snap install --classic aws-cli
  tags:
    - cloud
    - aws

- name: install AWS CLI tools via PIP
  pip:
    name: awscli
    extra_args: --upgrade
    state: latest
  tags:
    - cloud
    - aws

- name: install latest Azure CLI tools via SNAP
  command: snap install --candidate azure-cli
  tags:
    - cloud
    - azure
