---
# File: roles/cloud/tasks/main.yml

- name: remove AWS CLI tools from Debian repositories
  apt: name=awscli state=absent
  tags:
    - cloud
    - aws

- name: install latest AWS CLI tools via SNAP
  command: snap install --classic aws-cli
  tags:
    - cloud
    - aws

- name: install latest Azure CLI tools via SNAP
  command: snap install --candidate azure-cli
  tags:
    - cloud
    - azure
