---
# File: workstation.yml

- hosts: all
  remote_user: ansible
  become: yes
  roles:
    - common
    - development
    - java
    - netbeans
    - jmeter
    - zaproxy
    - burp_suite
    - sqlmap
    - firefox_de
    - google_chrome
    - dbeaver
    - apache_directory_studio
    - eclipse
    - umlet
    - soapui
