---
# File: workstation.yml

- hosts: all
  remote_user: ansible
  sudo: yes
  roles:
    - common
    - development
    - java
    - netbeans
    - jmeter
    - zaproxy
    - firefox_de
    - dbeaver
    - apache_directory_studio
    - eclipse
    - umlet

