---
# File: roles/firefox_de/tasks/main.yml

- name: create a directory for optional firefox-de software
  file: name=/opt/firefox-de state=directory
  tags:
    - firefox-de

- name: download latest version of Firefox Developer Edition (64-bit)
  uri: url=https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux64&lang=en-US
       dest=~/firefox-de.en-US.linux.tar.bz2
       creates=~/firefox-de.en-US.linux.tar.bz2
  when: ansible_architecture == "x86_64"
  tags:
    - firefox-de

- name: download latest version of Firefox Developer Edition (32-bit)
  uri: url=https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux&lang=en-US
       dest=~/firefox-de.en-US.linux.tar.bz2
       creates=~/firefox-de.en-US.linux.tar.bz2
  when: ansible_architecture == "i386"
  tags:
    - firefox-de

- name: install the latest version of Firefox Developer Edition
  shell: tar -C /opt/firefox-de -xjf ~/firefox-de.en-US.linux.tar.bz2
         creates=/opt/firefox-de/firefox
  tags:
    - firefox-de

- name: add a launcher to the development, network, etc menus
  copy: src=../files/firefox-de.desktop
        dest=/usr/share/applications
  tags:
    - firefox-de

