# Go

# https://dl.google.com/go/go1.11.2.linux-amd64.tar.gz

go_host: "https://dl.google.com"
go_path: "go"
go_file: "go{{ go_version }}.linux-amd64.tar.gz"

go_url: "{{ go_host }}/{{ go_path }}/{{ go_file }}"

go_installation_directory: "/opt/go"
go_archive_directory: "{{ go_installation_directory }}/go"
go_home_directory: "{{ go_installation_directory }}/{{ go_version }}"
go_tools_directory: "/usr/share/go-tools"

# RFC

# https://raw.githubusercontent.com/bfontaine/rfc/v0.2.5/rfc

rfc_host: "https://raw.githubusercontent.com"
rfc_path: "bfontaine/rfc/v{{ rfc_version }}"
rfc_file: "rfc"

rfc_url: "{{ rfc_host }}/{{ rfc_path }}/{{ rfc_file }}"

rfc_installation_directory: "/opt/rfc"
rfc_home_directory: "{{ rfc_installation_directory }}/{{ rfc_version }}"
