---

- name: enable apk community repository
  lineinfile:
    path: /etc/apk/repositories
    regexp: "^#(http://.*/alpinelinux/)v([0-9.]*)/{{ item }}"
    backrefs: "yes"
    line: "\\1v\\2/{{ item }}" 
    state: "present"
  with_items:
  - "main"
  - "community"
  when: "ansible_distribution == 'Alpine'"

- name: enable apk edge repositories
  lineinfile:
    path: /etc/apk/repositories
    regexp: "^#(http://.*/alpinelinux/)edge/{{ item }}"
    backrefs: "yes"
    line: "\\1edge/{{ item }}" 
    state: "present"
  with_items:
  - "main"
  - "community"
  - "testing"
  when: "ansible_distribution == 'Alpine'"

# unarchive requires tar, unzip
- name: "add Python libraries required by Ansible"
  apk:
    name: "tar,unzip"
    state: "present"
  when: "ansible_distribution == 'Alpine'"

...
