---

- name: enable additional apk repositories
  lineinfile:
    path: /etc/apk/repositories
    regexp: "^#(http://.*/alpinelinux/)"
    backrefs: "yes"
    line: "\\1{{ item }}" 
    state: "present"
  with_items:
  - "v3.10/main"
  - "v3.10/community"
  - "edge/main"
  - "edge/community"
  - "edge/testing"
  when: "ansible_distribution == 'Alpine'"

...
