---
# File: roles/development/tasks/main.yml

#
# Languages
#

- name: add languages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - golang-{{ go_version }}
    - golang-golang-x-tools
  tags:
    - languages

- name: set-up the go environment
  template:
    src=../files/go.sh
    dest=/etc/profile.d
  tags:
    - languages
    - go

- name: add useful go packages
  shell: /usr/lib/go-{{ go_version }}/bin/go get -u {{ item }}
  with_items:
    - "github.com/uudashr/gopkgs/cmd/gopkgs"
  tags:
    - languages
    - go

#
# Editors
#

- name: add the full-featured versions of vim
  apt: name={{ item }} state=present
  with_items:
    - vim
    - vim-gnome
  tags:
    - editors
    - vim

- name: add the typora signing key
  apt_key: keyserver=keyserver.ubuntu.com id=BA300B7755AFCFAE
           state=present
  tags:
    - editors

- name: add the typora repository
  apt_repository: repo='deb https://typora.io linux/'
                  state=present
                  mode=644
  tags:
    - editors

- name: update the repository cache
  apt: update_cache=yes
  tags:
    - editors

- name: install typora
  apt: pkg=typora state=present
  tags:
    - editors
    
#
# NodeJS
#

- name: add the NodeJS signing key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
           state=present

- name: add the NodeJS repositories
  apt_repository: repo={{ item }}
                  state=present
                  mode=644
  with_items:
    - deb https://deb.nodesource.com/{{ nodejs_repo }} bionic main
    - deb-src https://deb.nodesource.com/{{ nodejs_repo }} bionic main
    
- name: add NodeJS (and therefore NPM)
  apt: name=nodejs state=latest update_cache=yes

#
# Virtualization
#

- name: install virtualization tools
  apt: name={{ item }} state=latest
  with_items:
#    - ansible
    - vagrant
    - virtualbox
    - virtualbox-qt
  tags:
    - virtualization

#
# Source Code Management
#

- name: install linux tools for git
  apt: name={{ item }} state=latest
  with_items:
    - git
    - git-doc
    - git-svn
  tags:
    - git

#
# Install Meld
#
- name: install meld
  apt: name=meld state=latest
  tags:
    - git
    - meld


- name: install linux tools for Subversion
  apt: name={{ item }} state=latest
  with_items:
    - subversion
    - libsvn-java
  tags:
    - subversion
 

#
# Build tools
#

- name: install Java build tools
  apt: name={{ item }} state=latest
  with_items:
    - ant
    - gradle
    - maven

#
# File formating tools
#

- name: install file formating tools
  apt: name={{ item }} state=latest
  with_items:
    - python-demjson

#
# LDAP tools
#

- name: install linux tools for LDAP
  apt: name={{ item }} state=latest
  with_items:
    - ldap-utils
    - ldapvi
  tags:
    - ldap

#
# Networking
#

- name: add packages that are useful when developing networking software
  apt: name={{ item }} state=latest
  with_items:
    - wireshark
    - zenmap
  tags:
    - networking

#
# Graphics
#

- name: add packages that are useful for designing UIs
  apt: name={{ item }} state=latest
  with_items:
    - gpick
    - gimp
    - inkscape
    - screenruler
  tags:
    - graphics

#
# Inform
#

- name: add packages needed to develop and run IF games
  apt: name={{ item }} state=latest
  with_items:
    - zoom-player
    - inform
    - inform-docs
  tags:
    - interactive-fiction
    - inform
