---
# File: roles/development/tasks/main.yml

#
# Virtualization
#

- name: install virtualization tools
  apt: name={{ item }} state=latest
  with_items:
#    - ansible
    - vagrant
    - virtualbox
  tags:
    - virtualization

#
# Containerization
#

- name: install docker for container execution environment
  apt: name=docker.io state=latest

- name: create the installation directory for Kubernetes
  file: name="/opt/kubernetes" state="directory"

#
# Source Code Management
#

- name: install linux tools for git
  apt: name={{ item }} state=latest
  with_items:
    - git
    - git-doc
    - git-svn
  tags:
    - git

- name: install linux tools for Subversion
  apt: name={{ item }} state=latest
  with_items:
    - subversion
    - libsvn-java
  tags:
    - subversion
    
#
# Build tools
#

- name: install Java build tools
  apt: name={{ item }} state=latest
  with_items:
    - ant
    - gradle
    - maven
    - nodejs-legacy

#
# File formating tools
#

- name: install file formating tools
  apt: name={{ item }} state=latest
  with_items:
    - python-demjson

#
# LDAP tools
#

- name: install linux tools for LDAP
  apt: name={{ item }} state=latest
  with_items:
    - ldap-utils
  tags:
    - ldap

#
# Networking
#

- name: add packages that are useful when developing networking software
  apt: name={{ item }} state=latest
  with_items:
    - wireshark
    - zenmap
  tags:
    - networking

#
# Graphics
#

- name: add packages that are useful for designing UIs
  apt: name={{ item }} state=latest
  with_items:
    - gcolor2
    - inkscape
    - screenruler
  tags:
    - graphics
