---
# File: roles/development/tasks/main.yml

#
# Virtualization
#

- name: install virtualization tools
  apt: name={{ item }} state=latest
  with_items:
    - ansible
    - vagrant
    - virtualbox
  tags:
    - virtualization

#
# Source Code Management
#

- name: install linux tools for git
  apt: name={{ item }} state=latest
  with_items:
    - git
    - git-doc
    - git-svn
  tags:
    - git

- name: install linux tools for Subversion
  apt: name={{ item }} state=latest
  with_items:
    - subversion
    - libsvn-java
  tags:
    - subversion
    
#
# Build tools
#

- name: install Java build tools
  apt: name={{ item }} state=latest
  with_items:
    - ant
    - maven

#
# LDAP tools
#

- name: install linux tools for LDAP
  apt: name={{ item }} state=latest
  with_items:
    - ldap-utils
  tags:
    - ldap

#
# Networking
#

- name: add packages that are useful when developing networking software
  apt: name={{ item }} state=latest
  with_items:
    - wireshark
    - zenmap
  tags:
    - networking

