---
# File: roles/development/tasks/main.yml

#
# Virtualization
#

- name: install virtualization tools
  apt: name={{ item }} state=latest
  with_items:
    - ansible
    - vagrant
    - virtualbox
  tags:
    - virtualization

#
# Source Code Management
#

- name: install linux tools for git
  apt: name={{ item }} state=latest
  with_items:
    - git
    - git-doc
    - git-svn
  tags:
    - git

- name: install linux tools for Subversion
  apt: name={{ item }} state=latest
  with_items:
    - subversion
    - libsvn-java
  tags:
    - subversion
    
#
# Build tools
#

- name: install Java build tools
  apt: name={{ item }} state=latest
  with_items:
    - ant
    - maven

#
# LDAP tools
#

- name: install linux tools for LDAP
  apt: name={{ item }} state=latest
  with_items:
    - ldap-utils
  tags:
    - ldap

#
# Networking
#

- name: add packages that are useful when developing networking software
  apt: name={{ item }} state=latest
  with_items:
    - wireshark
    - zenmap
  tags:
    - networking

#
# Firefox Developer Edition
#

- name: create a directory for optional firefox-de software
  file: name=/opt/firefox-de state=directory
  tags:
    - firefox-de

- name: download latest version of Firefox Developer Edition (64-bit)
  uri: url=https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux64&lang=en-US
       dest=~/firefox-de.en-US.linux.tar.bz2
       creates=~/firefox-de.en-US.linux.tar.bz2
  when: ansible_architecture == "x86_64"
  tags:
    - firefox-de

- name: download latest version of Firefox Developer Edition (32-bit)
  uri: url=https://download.mozilla.org/?product=firefox-aurora-latest-ssl&os=linux&lang=en-US
       dest=~/firefox-de.en-US.linux.tar.bz2
       creates=~/firefox-de.en-US.linux.tar.bz2
  when: ansible_architecture == "i386"
  tags:
    - firefox-de

- name: install the latest version of Firefox Developer Edition
  shell: tar -C /opt/firefox-de -xjf ~/firefox-de.en-US.linux.tar.bz2
         creates=/opt/firefox-de/firefox
  tags:
    - firefox-de

- name: add a launcher to the development, network, etc menus
  copy: src=../files/firefox-de.desktop
        dest=/usr/share/applications
  tags:
    - firefox-de

#
# Zed Attack Proxy
#

- name: create a directory for optional Zed Attack Proxy software
  file: name=/opt/zaproxy state=directory
  tags:
    - zaproxy

- name: download latest version of the Zed Attack Proxy
  uri: url=http://sourceforge.net/projects/zaproxy/files/2.4.0/ZAP_2.4.0_Linux.tar.gz/download
       dest=~/ZAP_2.4.0_Linux.tar.gz
       creates=~/ZAP_2.4.0_Linux.tar.gz
  tags:
    - zaproxy

- name: install the latest version of the Zed Attack Proxy
  shell: tar -C /opt/zaproxy -xzf ~/ZAP_2.4.0_Linux.tar.gz
         creates=/opt/zaproxy/ZAP_2.4.0
  tags:
    - zaproxy

- name: add a launcher for the Zed Attack Proxy to the development menu
  copy: src=../files/zaproxy.desktop
        dest=/usr/share/applications
  tags:
    - zaproxy

