---
# File: roles/java/tasks/main.yml

#
# OpenJDK
#
  
- name: "install the latest OpenJDK"
  apt:
    name: "{{ packages }}"
    state: "latest"
  vars:
    packages:
    - "openjdk-{{ java_version }}-jdk"
    - "openjdk-{{ java_version }}-demo"
    - "openjdk-{{ java_version }}-source"
    - "openjdk-{{ java_version }}-doc"
  tags:
    - "java"

#
# Set up the java alternatives to point to OpenJDK
#

      #- name: set up the java alternatives to point to OpenJDK 8
      #alternatives: name={{ item.name }} path={{ item.path }}
      #with_items: "{{ java_alternatives }}"
      #tags:
      #- java
  
