---
# File: roles/zaproxy/tasks/main.yml

- name: create a directory for optional Zed Attack Proxy software
  file: name=/opt/zaproxy state=directory
  tags:
    - zaproxy

- name: download latest version of the Zed Attack Proxy
  uri: url={{ zaproxy_url }}
       dest=~/{{ zaproxy_file }}
       creates=~/{{ zaproxy_file }}
  tags:
    - zaproxy

- name: untar the Zed Attack Proxy archive
  unarchive: copy=no
             src=~/{{ zaproxy_file }}
             dest={{ zaproxy_installation_directory }}
             creates={{ zaproxy_home_directory }}
  register: unarchive_result
  tags:
    - zaproxy

- name: move the tar file's base directory somewhere maintainable
  command: mv {{ zaproxy_tar_directory }}
           {{ zaproxy_home_directory }}
  when: unarchive_result is changed
  tags:
    - zaproxy

- name: create a pretty symlink to the latest version
  file: src={{ zaproxy_home_directory }}
        path={{ zaproxy_installation_directory }}/latest
        state=link
  tags:
    - zaproxy

- name: add a launcher for the Zed Attack Proxy to the development menu
  template: src=../files/zaproxy.desktop
            dest=/usr/share/applications
  tags:
    - zaproxy
