---
# File: roles/zaproxy/tasks/main.yml

- name: create a directory for optional Zed Attack Proxy software
  file: name=/opt/zaproxy state=directory
  tags:
    - zaproxy

- name: download latest version of the Zed Attack Proxy
  uri: url=http://sourceforge.net/projects/zaproxy/files/2.4.0/ZAP_2.4.0_Linux.tar.gz/download
       dest=~/ZAP_2.4.0_Linux.tar.gz
       creates=~/ZAP_2.4.0_Linux.tar.gz
  tags:
    - zaproxy

- name: install the latest version of the Zed Attack Proxy
  shell: tar -C /opt/zaproxy -xzf ~/ZAP_2.4.0_Linux.tar.gz
         creates=/opt/zaproxy/ZAP_2.4.0
  tags:
    - zaproxy

- name: add a launcher for the Zed Attack Proxy to the development menu
  copy: src=../files/zaproxy.desktop
        dest=/usr/share/applications
  tags:
    - zaproxy

