---
# File: roles/containerization/tasks/main.yml

#
# Docker
#

- name: install docker for container execution environment
  apt: name=docker.io state=latest
  tags:
    - containerization
    - docker

#
# Delete the full Kubernetes installation
#

- name: delele Kubernetes
  file: name={{ k8s_installation_directory }} state="absent"
  tags:
    - containerization
    - kubernetes

#
# Install only kubectl
#

- name: "add the google apt key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: "present"
  tags:
    - containerization
    - kubernetes

- name: "add the Google repository"
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: "present"
  tags:
    - containerization
    - kubernetes

- name: "install kubectl"
  apt:
    name: "kubectl"
    state: "present"
    update_cache: "yes"
  tags:
    - containerization
    - kubernetes

#
# HyperKube is now deprecated in favor of MiniKube
#

- name: remove the directory for the convenience scripts
  file: name={{ k8s_installation_directory }}/scripts state=directory
        state=absent
  tags:
    - containerization
    - kubernetes

- name: remove scripts from the user's path
  file: path={{ item }}
        state=absent
  with_items:
    - /usr/bin/kube-up
    - /usr/bin/kube-down
  tags:
    - containerization
    - kubernetes

- name: create the installation directory for MiniKube
  file: name={{ minikube_home_directory }} state=directory
  tags:
    - containerization
    - kubernetes
    - minikube

- name: download the MiniKube executable
  uri: url={{ minikube_url }}
       dest="{{ minikube_home_directory }}/{{ minikube_file }}"
       creates="{{ minikube_home_directory }}/{{ minikube_file }}"
       mode=755
  register: download_result
  tags:
    - containerization
    - kubernetes
    - minikube

- name: create a pretty symlink to the latest MiniKube version
  file: src={{ minikube_home_directory }}
        path={{ minikube_installation_directory }}/latest
        state=link
  when: download_result | changed
  tags:
    - containerization
    - kubernetes
    - minikube

- name: put minikube on the user's path
  file: src={{ minikube_installation_directory }}/latest/{{ minikube_file }}
        path=/usr/bin/minikube
        state=link
  tags:
    - containerization
    - kubernetes
    - minikube

