---
# File: roles/common/tasks/main.yml

- name: update the repository caches
  apt: update_cache=yes
  
- name: upgrade existing apt packages
  apt: upgrade=safe

- name: install basic Linux tools
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - tree
    - whois
    
- name: install the NTP daemon (on Mint ... it's not installed by default)
  apt: name=ntp state=latest

