---
# File: roles/common/tasks/main.yml

- name: update the repository caches
  apt: update_cache=yes
  
- name: upgrade existing apt packages
  apt: upgrade=yes state=latest

- name: install basic Linux tools
  apt: name={{ item }} state=latest
  with_items:
    - curl
    - npm
    - seahorse
    - traceroute
    - tree
    - vlc
    - whois
    
- name: install the NTP daemon (on Mint ... it's not installed by default)
  apt: name=ntp state=latest

# Add f.lux (see https://justgetflux.com/linux.html)

- name: add the f.lux repository
  apt_repository: repo='deb http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main '
                  state=present
  
- name: add the f.lux source repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main '
                  state=present
                  
- name: add the f.lux signing key
  apt_key: keyserver=keyserver.ubuntu.com id=e602b5ddea4951fb628e7bd4faeb83059bd4ed25
  
- name: update the apt repositories to include the new f.lux packages
  apt: upgrade=safe
  
- name: install f.lux
  apt: name=fluxgui state=present
