---
# File: roles/common/tasks/main.yml

- name: update the repository caches
  apt: update_cache=yes
  
- name: upgrade existing apt packages
  apt: upgrade=yes state=latest

- name: install basic Linux tools
  apt: name={{ item }} state=latest
  with_items:
    - asciinema
    - audacity
    - curl
    # - freemind
    # - freemind-plugins-svg
    - gparted
    - lynx
    - minicom
    - npm
    - recordmydesktop
    - screen
    - seahorse
    - secure-delete
    - sshfs
    - tftp
    - traceroute
    - tree
    - vlc
    - whois
    - wipe
    
- name: install the NTP daemon (on Mint ... it's not installed by default)
  apt: name=ntp state=latest

# Add f.lux (see https://justgetflux.com/linux.html)

- name: remove the old f.lux repository
  apt_repository: repo='deb http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main'
                  state=absent

- name: remove the old f.lux source repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/kilian/f.lux/ubuntu trusty main'
                  state=absent
                  
- name: remove the old f.lux signing key
  apt_key: keyserver=keyserver.ubuntu.com id=e602b5ddea4951fb628e7bd4faeb83059bd4ed25
           state=absent

- name: add the f.lux repository
  apt_repository: repo='deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main'
                  state=present
                  mode=644

- name: add the f.lux source repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu xenial main'
                  state=present
                  mode=644

- name: add the f.lux signing key
  apt_key: keyserver=keyserver.ubuntu.com id=428926204FE30238F00B98224CDB129629A4B41A
           state=present

- name: update the apt repositories to include the new f.lux packages
  apt: update_cache=yes

- name: install f.lux
  apt: name=fluxgui state=present
