---
# File: roles/common/tasks/main.yml

- name: update the repository caches
  apt: update_cache=yes
  
- name: upgrade existing apt packages
  apt: upgrade=yes state=latest

# Mint does not ship with snap
- name: ensure snap is installed
  apt: name=snapd state=latest

- name: refresh the existing snap packages
  command: snap refresh

- name: install basic Linux tools
  apt: name={{ item }} state=latest
  with_items:
    - asciinema
    - audacity
    - curl
    - gparted
    - hopenpgp-tools
    - lynx
    - minicom
    - parcimonie
    - pass
    - qtpass
    - recordmydesktop
    - screen
    - seahorse
    - secure-delete
    - snapd
    - sshfs
    - sshuttle
    - tftp
    - traceroute
    - tree
    - vlc
    - whois
    - wipe

- name: install freemind via snap
  command: snap install freemind
  tags:
    - freemind

- name: copy the freemind icon
  copy:
    src: ../files/freemind.png
    dest: /snap/bin
  tags:
    - freemind

- name: add the freemind desktop item to the menu
  copy:
    src: ../files/freemind.desktop
    dest: /usr/share/applications
  tags:
    - freemind
    
- name: install the NTP daemon (on Mint ... it's not installed by default)
  apt: name=ntp state=latest
  
# Add f.lux (see https://justgetflux.com/linux.html)

- name: add the f.lux signing key
  apt_key: keyserver=keyserver.ubuntu.com id=428926204FE30238F00B98224CDB129629A4B41A
           state=present

- name: add the f.lux repository
  apt_repository: repo='deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main'
                  state=present
                  mode=644

- name: add the f.lux source repository
  apt_repository: repo='deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main'
                  state=present
                  mode=644

- name: update the apt repositories to include the new f.lux packages
  apt: update_cache=yes

- name: install f.lux
  apt: name=fluxgui state=present
