---
# File: roles/containerization/vars/main.yml

#
# Kubernetes
#

# This is still needed solely to delete previous workstation installs of Kubernetes
k8s_name: kubernetes
k8s_installation_directory: /opt/{{ k8s_name }}

# https://storage.googleapis.com/minikube/releases/v0.6.0/minikube-linux-amd64

minikube_host: https://storage.googleapis.com
minikube_path: minikube/releases/v{{ minikube_version }}
minikube_file: minikube-linux-amd64

minikube_url: "{{ minikube_host }}/{{ minikube_path }}/{{ minikube_file }}"

minikube_installation_directory: /opt/minikube
minikube_home_directory: "{{ minikube_installation_directory }}/{{ minikube_version }}"

# https://github.com/ahmetb/kubectx/archive/v0.5.0.tar.gz

kubectx_host: "https://github.com"
kubectx_path: "ahmetb/kubectx/archive"
kubectx_file: "v{{ kubectx_version }}.tar.gz"

kubectx_url: "{{ kubectx_host }}/{{ kubectx_path }}/{{ kubectx_file }}"

kubectx_installation_directory: "/opt/kubectx"
kubectx_home_directory: "{{ kubectx_installation_directory }}/{{ kubectx_version }}"

kubectx_executables:
  - "kubectx"
  - "kubens"

# https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz
# https://storage.googleapis.com/kubernetes-helm/helm-v2.9.1-linux-amd64.tar.gz.sha256
# https://raw.githubusercontent.com/kubernetes/helm/v2.9.1/scripts/completions.bash

helm_host: "https://storage.googleapis.com"
helm_path: "kubernetes-helm"
helm_file: "helm-v{{ helm_version }}-linux-amd64.tar.gz"

helm_url: "{{ helm_host }}/{{ helm_path }}/{{ helm_file }}"

helm_installation_directory: "/opt/helm"
helm_home_directory: "{{ helm_installation_directory }}/{{ helm_version }}"

helm_bash_host: "https://raw.githubusercontent.com"
helm_bash_path: "kubernetes/helm/v{{ helm_version }}/scripts"
helm_bash_file: "completions.bash"

helm_bash_url: "{{ helm_bash_host }}/{{ helm_bash_path }}/{{ helm_bash_file }}"
