---

# Add Visual Studio Code (see https://code.visualstudio.com/docs/setup/linux)

- name: add the visual studio signing key
  apt_key: url={{ vs_key }}
           state=present
  tags:
  - visual_studio
  - ide
  - editor

- name: add the visual studio repository
  apt_repository: repo={{ vs_repository }}
                  state=present
                  mode=644
  tags:
  - visual_studio
  - ide
  - editor

- name: install visual studio
  apt: name=code state=present update_cache=yes
  tags:
  - visual_studio
  - ide
  - editor

- name: install selected visual studio extensions
  shell: code --install-extension {{ item }} --user-data-dir /usr/share/code
  with_items:
  - vscodevim.vim
  - vscjava.vscode-java-pack
  - vscjava.vscode-maven
  tags:
  - visual_studio
  - ide
  - editor

...