---
# File roles/netbeans/tasks/main.yml

- name: create a directory for optional Netbeans IDE software
  file: name={{ netbeans_installation_directory }}
        state=directory
  tags:
    - netbeans

- name: download the Netbeans IDE archive
  uri: url={{ netbeans_url }}
       dest=~/{{ netbeans_file }}
       creates=~/{{ netbeans_file }}
  tags:
    - netbeans

- name: unzip the Netbeans distribution
  unarchive: copy=no
             src=~/{{ netbeans_file }}
             dest={{ netbeans_installation_directory }}
             creates={{ netbeans_home_directory }}
  register: unarchive_result
  tags:
    - netbeans

- name: move the ZIP file's base directory somewhere maintainable
  command: mv {{ netbeans_zip_directory }}
           {{ netbeans_home_directory }}
  when: unarchive_result is changed
  tags:
    - netbeans

- name: create a pretty symlink to the latest version
  file: src={{ netbeans_home_directory }}
        path={{ netbeans_installation_directory }}/latest
        state=link
  tags:
    - netbeans

- name: add a launcher for Netbeans to the development menu
  template: src=../files/netbeans.desktop
            dest=/usr/share/applications
  tags:
    - netbeans
